---

- name: Join RHEL server to Active Directory domain using root

  hosts: all

  gather_facts: true

  vars:

    domain_user: 'WINTEL@UBAGROUP.COM'

    domain_password: '{{ vault_domain_password }}'

    domain: 'ubagroup.com'

    realm: 'UBAGROUP.COM'

    ad_group: 'wintelvirtualizationteam'
 
  tasks:

    - name: Ensure required packages are installed

      package:

        name:

          - realmd

          - sssd

          - oddjob

          - oddjob-mkhomedir

          - adcli

          - samba-common

          - samba-common-tools

          - krb5-workstation

          - sssd-tools

        state: present
 
    - name: Ensure NTP is installed and enabled

      package:

        name: chrony

        state: present
 
    - name: Enable and start chronyd

      systemd:

        name: chronyd

        state: started

        enabled: true
 
    - name: Discover the domain

      command: realm discover {{ domain }}

      register: realm_discover

      changed_when: false
 
    - name: Join the server to the domain

      expect:

        command: realm join -U {{ domain_user }} {{ domain }}

        responses:

          Password for {{ domain_user }}: "{{ domain_password }}"

      register: join_output

      no_log: true
 
    - name: Permit AD group to log in

      command: realm permit -g {{ ad_group }}

      when: join_output.rc == 0
 
    - name: Ensure SSSD service is enabled and running

      systemd:

        name: sssd

        state: started

        enabled: true
 
    - name: Configure mkhomedir to create home dirs on login

      lineinfile:

        path: /etc/sssd/sssd.conf

        regexp: '^.*pam_mkhomedir.so.*'

        line: 'session optional pam_mkhomedir.so skel=/etc/skel/ umask=0077'

        insertafter: '[pam]'

        create: yes

      notify: restart sssd
 
  handlers:

    - name: restart sssd

      systemd:

        name: sssd

        state: restarted
 
